[workspace]
members = ["core", "app-macos", "app-linux", "app-windows"]
resolver = "2"

[workspace.package]
version = "1.7.0"
edition = "2024"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
